name: mysnap-simosx
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: My Snap
description: |
  This is the My Snap demonstration snap package. We use this to demonstrate
  building snaps on build.snapcraft.io

grade: stable
confinement: strict

apps:
  mysnap:
    command: mysnap

parts:
  mysnap:
    source: .
    plugin: make
